#!/bin/bash
DIR=/var/www/shop_development
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=production nohup "$NODE" "$DIR/cluster.js" 1>>"$DIR/logs/shop.log" 2>&1 &
  echo $! > "$DIR/pids/shop.pid"
}

function stop_app {
  kill `cat $DIR/pids/shop.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: shop {start|stop}" ;;
esac
exit 0